const allTeams = [
  {
    id: 1,
    title: 'Marketing 💸',
    body: 'Ad campaigns, newsletters, apparel and E-commerce',
    people: [{ shortName: 'AB' }, { shortName: 'CD' }, { shortName: 'EF' }],
  },
  {
    id: 2,
    title: 'Strategy 📈',
    body:
      'The goals and objectives, the type of products/services that we plan to build',
    people: [
      { shortName: 'CD' },
      { shortName: 'EF' },
      { shortName: 'AB' },
      { shortName: 'GH' },
      { shortName: 'TL' },
      { shortName: 'XA' },
      { shortName: 'YD' },
    ],
  },
  {
    id: 3,
    title: 'Core Product 💎',
    body: 'Building the product',
    people: [{ shortName: 'AB' }, { shortName: 'CD' }],
  },
  {
    id: 4,
    title: 'Dev 👨‍💻',
    body: 'Dev teams and Tech stuff',
    people: [
      { shortName: 'EF' },
      { shortName: 'XA' },
      { shortName: 'AB' },
      { shortName: 'CD' },
      { shortName: 'YD' },
    ],
  },
  {
    id: 5,
    title: 'Component Lib 📖',
    body: 'Building the foundation of all new products',
    people: [
      { shortName: 'GH' },
      { shortName: 'EF' },
      { shortName: 'TL' },
      { shortName: 'XA' },
      { shortName: 'YD' },
    ],
  },
  {
    id: 6,
    title: 'Team Winning 💯',
    body: 'The best working team in office',
    people: [
      { shortName: 'CD' },
      { shortName: 'GH' },
      { shortName: 'TL' },
      { shortName: 'XA' },
      { shortName: 'YD' },
    ],
  },
];

const allProjects = [
  {
    id: 4,
    title: 'Innovation pitch 👩‍🏫',
    body: `What is the expected positive effect for our business? This may be tangible or intangible, and ideally both.`,
    people: [
      { shortName: 'EF' },
      { shortName: 'XA' },
      { shortName: 'AB' },
      { shortName: 'CD' },
      { shortName: 'YD' },
      { shortName: 'EF' },
      { shortName: 'XA' },
      { shortName: 'AB' },
      { shortName: 'CD' },
      { shortName: 'YD' },
      { shortName: 'EF' },
      { shortName: 'XA' },
      { shortName: 'AB' },
      { shortName: 'CD' },
      { shortName: 'YD' },
      { shortName: 'EF' },
      { shortName: 'XA' },
      { shortName: 'AB' },
      { shortName: 'CD' },
      { shortName: 'YD' },
      { shortName: 'EF' },
      { shortName: 'XA' },
      { shortName: 'AB' },
      { shortName: 'CD' },
      { shortName: 'YD' },
      { shortName: 'EF' },
      { shortName: 'XA' },
      { shortName: 'AB' },
      { shortName: 'CD' },
      { shortName: 'YD' },
      { shortName: 'EF' },
      { shortName: 'XA' },
      { shortName: 'AB' },
      { shortName: 'CD' },
      { shortName: 'YD' },
    ],
  },
  {
    id: 1,
    title: 'Tech Meetup 💻',
    body: 'A collective meetup to discuss all upcoming trends in software',
    people: [{ shortName: 'AB' }, { shortName: 'CD' }, { shortName: 'EF' }],
  },
  {
    id: 2,
    title: 'Beach party 🏖',
    body: 'Organizing all the food, music and good vibes',
    people: [
      { shortName: 'CD' },
      { shortName: 'EF' },
      { shortName: 'AB' },
      { shortName: 'GH' },
      { shortName: 'TL' },
      { shortName: 'XA' },
      { shortName: 'YD' },
    ],
  },
  {
    id: 3,
    title: 'SLA 🛒',
    body: 'Service level agreements with all clients',
    people: [{ shortName: 'AB' }, { shortName: 'CD' }],
  },
];

const companyNews = [
  {
    id: 0,
    title: 'Welcome! 👋',
    body: 'This dashboard will help you with all the information you need.',
  },
  {
    id: 1,
    title: '𝐅𝐚𝐛𝐫𝐢𝐪𝐮𝐞 𝐧𝐞𝐰𝐬',
    body: 'Company-wide announcements and stuff everyone needs to know.',
  },
];

export { allTeams, allProjects, companyNews };
